Feature comments
Brill1983/java-explore-with-me pull request #5
Opened 2023-11-03 14:02 UTC by Brill1983

2023-11-03 15:39 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/AdminCommentController.java
> +    public void deleteCommentByAdmin(@PathVariable long commentId) {
Вообще название в заблуждение вводит. Вы же не по админу удаляете, а по ид комментария =) а по названию метода как будто по админу.

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/AdminCommentController.java
> +@Validated
А для чего тут она?

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentMapper.java
> +public class CommentMapper {
Можно повесить аннотацию UtilityClass

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentMapper.java
> +    public static CommentShortDto toShortDto(Comment comment, EventShortDto eventDto) {
На мой взгляд, лучше через билдер создавать ДТОшки

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentRepository.java
> +    List<Comment> findByAuthor_IdAndEvent_Id(long userId, long eventId);
Используйте один формат нэйминга методов, лучше называть их camelCase-ом - будет работать

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentRepository.java
> +    @Query("select c.event.id as eventId, count(c.id) as commentsQuantity from Comment c where c.event.id in ?1 group by c.event.id")
А без Query у вас не работает? ЧИсто по названию метода

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentService.java
> +
Лишний пропуск строки

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +    // _______________________________ Private _________________________________________________________________________
Лично мне не очень нравятся такие вещи в коде, если у вас есть какое то жесткое разделение на private/public, то вообще лучше 2 разных сервиса делать

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        userRepository.findById(userId)
Сделайте метод existUserById использовать метод поиска для проверки наличия не очень хорошая практика

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId)
Вообще у вас поиск почти в каждом методе идет. Сделайте приватный метод, будет компактнее

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        if (CommentSort.valueOf(sort.toUpperCase()).equals(CommentSort.DESC)) {
Можно заменить на тернарное выражение - будет компактнее

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/utils/ErrorHandler.java
> +//    @ExceptionHandler
НУжно убрать

2023-11-03 15:39 UTC, Frilock commented on ewm-service/src/main/resources/schema.sql
> +    id    bigint generated by default as identity primary key,
Выровняйте форматирование

2023-11-03 19:12 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/AdminCommentController.java
> +    public void deleteCommentByAdmin(@PathVariable long commentId) {
Исправил

2023-11-03 19:12 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentMapper.java
> +public class CommentMapper {
Переделал

2023-11-03 19:12 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentRepository.java
> +    List<Comment> findByAuthor_IdAndEvent_Id(long userId, long eventId);
Исправил

2023-11-03 19:13 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/AdminCommentController.java
> +@Validated
Исправил

2023-11-03 19:13 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentMapper.java
> +    public static CommentShortDto toShortDto(Comment comment, EventShortDto eventDto) {
Поменял

2023-11-03 19:13 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentService.java
> +
Исправил

2023-11-03 19:13 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +    // _______________________________ Private _________________________________________________________________________
Исправил

2023-11-03 19:14 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        userRepository.findById(userId)
Исправил

2023-11-03 19:14 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId)
Исправил

2023-11-03 19:14 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentServiceImpl.java
> +        if (CommentSort.valueOf(sort.toUpperCase()).equals(CommentSort.DESC)) {
Поменял

2023-11-03 19:14 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/utils/ErrorHandler.java
> +//    @ExceptionHandler
Удалил

2023-11-03 19:14 UTC, Brill1983 commented on ewm-service/src/main/resources/schema.sql
> +    id    bigint generated by default as identity primary key,
Сделал

2023-11-04 08:23 UTC, Brill1983 commented on ewm-service/src/main/java/ru/practicum/comment/CommentRepository.java
> +    @Query("select c.event.id as eventId, count(c.id) as commentsQuantity from Comment c where c.event.id in ?1 group by c.event.id")
Без @Query не получается вернуть данные в виде мапы - где номер ID события соотносится с подсчитанным количеством комментариев.

2023-11-04 09:59 UTC, Frilock approved these changes
Принято, поздравляю с завершением курса и желаю всяческих успехов в дальнейшем развитии

2023-11-04 20:33 UTC, merged